### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by rostislav-rocket** [w3co/jcf#1]
Whenever html element has css rule "direction:rtl" styled select does not work properly (page content disappears on click on styled select). It's reproducible on any page by adding
```
html {direction:rtl}
```

 For example, try it on your demo page https://github.com/w3co/jcf/blob/master/index.html

**Comment by inferpse** [comment]
Hi!

That was a silly typo in `jcf.js`. It's fixed in master branch now.

Please note that the default theme called **"theme-minimal"** doesn't include styles for RTL layout. These styles can be handled with the help of the following class: **"jcf-rtl"**

```html
<html class="jcf-rtl">
```

**Comment by rostislav-rocket** [comment]
Thanks, :+1:
