### ISSUE TITLE
Select is returning wrong value on Firefox when using 'Tab' 

### ISSUE THREAD

**Issue by adamdilibero** [w3co/jcf#11]
When tabbing through a form in Firefox and coming across a select field Upon pressing the down arrow and reaching the desired value and pressing the 'Tab' key to move to the next field, the value is being incremented by 1

Example: 

Day:

03 was selected, press the tab key the focus moves to the month select next to it, but makes the day 04 when it was previously 03

Any ideas on this?

**Comment by inferpse** [comment]
Hi @adamdilibero !

Which versions of JCF and Firefox are you using? And what is your operating system?
I can't reproduce this issue with recent Firefox and JCF @1.2.0. Could you create a [fiddle](https://jsfiddle.net/) so we both can reproduce that issue?

Actually there's nothing special in keyboard handling - the script just updates the text value to the one that browser think is selected. Maybe you have some other scripts which are trying to modify select value when `change` event is occurred.

**Comment by adamdilibero** [comment]
Hi, 

Firefox Version: 40.0.3
JCF: 1.2.0 

jsFiddle: https://jsfiddle.net/k056xn67/

As part of our debugging we tried disabling jcf.js code entirely and this issue no longer persisted so we believe it may be part of the issue. 

Excuse some of the bad formatting styling on the jsFiddle - The issue however can be replicated in this fiddle as mentioned above. 

Thanks,

**Comment by inferpse** [comment]
I've fixed this issue. Please update `jcf.select.js` from the master branch.
