### ISSUE TITLE
Bug in Chrome with wrapNativeOnMobile : true

### ISSUE THREAD

**Issue by asso1985** [w3co/jcf#12]
jcf.setOptions('Select', {

		wrapNative: false,

		wrapNativeOnMobile: true

	});

On Chrome the native options are shown instead of the custom ones.

The goal is to have native dropdown list in mobile but jcf ones in the desktop version.

Seems like with chrome this is not possible

**Comment by reesmcivor** [comment]
This could be to do with the detection of whether your device is a mobile. I found that firefox worked fine but when in chrome it thought it was a mobile. I think this is related to the fact my laptop is a touch screen.
