### ISSUE TITLE
JCF - Checkboxes not working properly with '[ ]' characters in name

### ISSUE THREAD

**Issue by adamdilibero** [w3co/jcf#13]
<span class="jcf-checkbox jcf-unchecked jcf-focus jcf-pressed"><span></span><input type="checkbox" name="resource_import_User[]" id="resource_import_User[]" value="read" title="read" style="position: absolute; height: 100%; width: 100%; opacity: 0; margin: 0px;"></span>

We are having an issue with using the [] characters in a name and jcf loading the correct state for these. 

Any ideas? 

JSfiddle: https://jsfiddle.net/xj1yde26/ 

Thanks

**Comment by inferpse** [comment]
Hi, @adamdilibero !

It seems to work fine with the most recent JCF library.
What version do you use? Can you create a [jsfiddle](http://jsfiddle.net/) with your version of JCF?

**Comment by adamdilibero** [comment]
Hi, 

I have confirmed we are using the latest jcf library. 

The issue is that jcf is applying the styling and looks correct however the form is not submitting with the inputs only when using '[]' in the name 

Thanks
