### ISSUE TITLE
How do you select a specific parent to use jcf on?

### ISSUE THREAD

**Issue by Puddingboy** [w3co/jcf#14]
What do I do if I want to select a specific div or section element to use jcf on? Will I have to select all elements in my div/section or are there options for jcf.replaceAll( [context] ) or jcf.replace( elements [, moduleName] [, customOptions] ) to do so?

Edit: I found the answer. I read poorly:
This should work:
var myDiv = $('#div');
jcf.replaceAll( myDiv );

This should also work:
var myClasses = $('.myClass');
jcf.replaceAll( myClasses );

Correct me if I'm wrong.

**Comment by inferpse** [comment]
@Puddingboy yes, that is correct :)
