### ISSUE TITLE
vertical and horizontal scroll

### ISSUE THREAD

**Issue by marmikdesai** [w3co/jcf#16]
I dont want vertical scroll. Is there way I can disable? So user can see horizontal scroll only.
<div class="scrollable-area">
    <ul class="jcf-scrollable">

   <ul>
</div>

**Comment by yazonnile** [comment]
As by default script detect what scroll should be visible and do it.
Result of this detection depends from your markup. If there is horizontal scroll in markup - after jcf apply there will be horizontal scroll. Both - both.

So there are two ways to remove vertical scroll.
1. remove vertical scrolling in your markup;
2. hide custom vertical scrollbar element via styles. Like this
```css
.jcf-scrollbar-vertical { display: none; }
```

**Comment by inferpse** [comment]
Looks like this one is resolved.
