### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by kino90** [w3co/jcf#18]
Hi! It would be nice if some cool themes were added! :+1:

**Comment by inferpse** [comment]
@kino90 good idea! We'll think about adding more themes.

Please note that the idea behind JCF is about flexible customization for specific design.
That's why we have only "minimal" theme which is used as a starting point for customization.

**Comment by kino90** [comment]
Sure, but it would be cool to have some themes like 'bootstrap', 'material design' and similar.. that are extra-cool as you download them, and also easy to import as scss and extend with custom colors and styles!

**Comment by yazonnile** [comment]
#57
