### ISSUE TITLE
AMD/RequireJS/CommonJS support useless for modules

### ISSUE THREAD

**Issue by TomRK1089** [w3co/jcf#2]
Looking at the "core" JCF file, I see that the script attempts to detect support for AMD loaders:

    (function(root, factory) {
	'use strict';
	if (typeof define === 'function' && define.amd) {
		define(['jquery'], factory);
	} else if (typeof exports === 'object') {
		module.exports = factory(require('jquery'));
	} else {
		root.jcf = factory(jQuery);
	}
    }(this, function($) {

This would be awesome...if any of the other plugins also did the same thing. However, they all expect that a global `jcf` object exists on the window. Scripts such as JQuery get around this by providing the global even when loaded by AMD, so that plugins can be shimmed (see http://requirejs.org/docs/api.html#config-shim). JCF's approach means that I am stuck between two unworkable options - if I don't load the core JCF script through RequireJS, it will cause an error when it attempts to call `define(['jquery'], factory)`, and if I do load it through RequireJS, I cannot load any of the plugins that make it useful.

Unless I'm missing something, the core script should export the global object in all circumstances.

**Comment by inferpse** [comment]
Hi, Tom!

Agreed. I've updated the master branch - SHA:006f258d0739d1947757be2e10a3af82317b9443 and tested with the following script:

```javascript
// configuration
requirejs.config({
    baseUrl: 'js',
    paths: {
        jquery: 'jquery',
        jcf: 'jcf'
    },
    shim: {
        'jcf.number': {
            deps: ['jcf'],
            exports: 'jcf.modules.Number'
        },
        'jcf.select': {
            deps: ['jcf'],
            exports: 'jcf.modules.Select'
        },
        'jcf.checkbox': {
            deps: ['jcf'],
            exports: 'jcf.modules.Checkbox'
        }
    }
});

// test
require(['jquery', 'jcf', 'jcf.select', 'jcf.checkbox', 'jcf.number'], function($, jcf) {
    $(function() {
        jcf.replaceAll();
    });
});
```

I'm going to add a few more fixes in modules and create a new release after that.

**Comment by TomRK1089** [comment]
Awesome, thanks for the quick turnaround!

**Comment by jirkae** [comment]
Hi,

plase, is this issue really fixed? Because when I have this code, it doesnt work

`requirejs.config({
	baseUrl: staticUrl+'js/ver2/',
	paths: {
		jcf: '../../bower_components/jcf/js/jcf',
		'jcf.checkbox': '../../bower_components/jcf/js/jcf.checkbox',
		'jcf.radio': '../../bower_components/jcf/js/jcf.radio',
		'jcf.select': '../../bower_components/jcf/js/jcf.select.min'
	},
	shim: {
		'imageFill': ['jquery'],
		'jcf.checkbox': {
            deps: ['jcf'],
            exports: 'jcf.modules.Checkbox'
        },
		'jcf.radio': {
            deps: ['jcf'],
            exports: 'jcf.modules.Radio'
        },
		'jcf.select': {
            deps: ['jcf'],
            exports: 'jcf.modules.Select'
		}
	}
});`

`
requirejs(['jcf','jcf.checkbox', 'jcf.radio', 'jcf.select'], function (jcf) {
					jcf.replaceAll(pluginInterface.jcf.conf.selector);
				});
`

Thanks a lot

**Comment by inferpse** [comment]
Hey, @jirkae !

What kind of error do you have? ```jcf is undefined``` and it's coming from one of the jcf modules?

**Comment by jirkae** [comment]
Oh, that was fast :D

`jcf.checkbox.js:171 Uncaught ReferenceError: jcf is not defined `

On each module

**Comment by inferpse** [comment]
Ok, I think we broke AMD compatibility with previous commit.
Try to use jcf.js from 79ec1a8. Will it work for you?

**Comment by jirkae** [comment]
Cool, thanks a lot, it works!
