### ISSUE TITLE
Add grunt tasks

### ISSUE THREAD

**Issue by danbopes** [w3co/jcf#24]
I would recommend looking into adding grunt, and simplifying some of your workflow.

A good example can be found here: https://github.com/chieffancypants/angular-loading-bar

They have a src folder, a build folder, and a way to automate tasks. One of the biggest downfalls of jcf is not being able to include a minified version of jcf through bower.

**Comment by inferpse** [comment]
Ok. I think this should be added in next major release because we can break compatibility for someone who used `/js/` path with bower.

**Comment by danbopes** [comment]
For the purposes of compatibility, you can keep the folders as is, and just create a dist/ folder for now. When you're ready to push a new version, then move the folder structure how you want.

If you'd like, I can make a pull request if it will help.

**Comment by inferpse** [comment]
@danbopes sorry, I was away for a while. Thank you for idea.
I'll add minified files and build system in the next release.

**Comment by inferpse** [comment]
Fixed in 1.2.2
