### ISSUE TITLE
Select performance

### ISSUE THREAD

**Issue by jirkae** [w3co/jcf#25]
Hello,
on mobile I have problem, that it takes around 6s to render selectbox. Checkbox and radio are fine. Any idea, what can cause the problem?

Thanks

**Comment by yazonnile** [comment]
Hi!
Could you plz attach any code-sample or screenshot?

**Comment by salunet** [comment]
Did you put the function inside a document.ready?

**Comment by inferpse** [comment]
@jirkae any information about it or we can close it? I suggest you to use default settings for selects. Let them show native dropdown on mobile devices - it will work fast and UX will be much better.

**Comment by jirkae** [comment]
Currently I am testing it with that fix, give me a minute, but it looks it is slow (entire JCF) :/ Tried run it just withou select and the performance was same. Without complete JCF the script was loaded in less than 2,5s

**Comment by jirkae** [comment]
Here is performance result:
![image](https://cloud.githubusercontent.com/assets/7256692/14706647/4b60c1a6-07c0-11e6-8cf5-a5999c414a42.png)

**Comment by jirkae** [comment]
Sorry, I didnt mention, that it is on mobile. PC can make it quite fast, but there must be something unoptimal

**Comment by jirkae** [comment]
Ok, so the problem is in number of inputs. I have around 200 checkboxes, so I need to add :visible to selector a refresh it on change. But 200 is not too many, isnt it?

**Comment by inferpse** [comment]
Well, for such cases I would highly recommend of thinking about using CSS approach.
Can you create a test page with similar behavior on https://jsfiddle.net/ so that we could reproduce it on mobile?

**Comment by inferpse** [comment]
Feel free to comment on this if you're still experiencing performance issues.
