### ISSUE TITLE
Angular 2 component

### ISSUE THREAD

**Issue by Ma3yTa** [w3co/jcf#28]
Please implement Angular 2 component

**Comment by inferpse** [comment]
@Ma3yTa I'll check this when final Angular 2 version will be released.

**Comment by konstrui** [comment]
Any news on this?

**Comment by dominiquemiller** [comment]
@inferpse, @konstrui  We use your plugin in our angular 1.x apps, we have migrated to angular 2.x.  I wrote a module to import JCF into angular 2.x projects.  https://github.com/TrimAgency/angular-jcf-module

**Comment by inferpse** [comment]
@dominiquemiller good job!
@Ma3yTa FYI
