### ISSUE TITLE
CSSStyleSheet.insertRule deprecation 

### ISSUE THREAD

**Issue by jujav4ik** [w3co/jcf#29]
Good day,

Implementing JCF on my Ember app, noted that I get constant warnings (in Chrome) on the deprecations for insertRule method.
insertRule started using [two arguments](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) in the function.

**Comment by inferpse** [comment]
Hey!

Fixed in new version. Thanks!
