### ISSUE TITLE
Input type range multiple value defaults to midpoint.

### ISSUE THREAD

**Issue by Rendez** [w3co/jcf#3]
Here:
https://github.com/w3co/jcf/blob/master/js/jcf.range.js#L454

I am unsure why you'd resort to get the realElement value passed index 0. For range "multiple" this would accuse a comma-separated value, which won't be of use to place the knob item in the right pixel.

Here:
http://www.wufoo.com/html5/attributes/08-multiple.html

We can see the next explanation for browsers that don't support yet the multiple attribute.
> range: Not yet supported, but added to the spec in April 2014, range input GUI will be able to support 2 sliders once the multiple attribute becomes supported. When the multiple attribute is supported on the range input type, the value will be two float numbers concatenated with a comma. When not supported, if a comma separated value is included, the value won't be understood, and will therefore be ignored. The value will then default to the midpoint.

**Comment by inferpse** [comment]
Hi, Luis!

Thank you for your pull request. That code was responsible for workaround the value problem in sliders with `multiple` attribute and it was used for testing purposes only.

**Comment by Rendez** [comment]
@inferpse no worries, will you bump a new version so we can use it with bower?

**Comment by inferpse** [comment]
@Rendez today I want to fix a few bugs in `select` and `scrollbar` modules. And right after that I'll create a new release :)
