### ISSUE TITLE
Not Working in Bootstrap tab 

### ISSUE THREAD

**Issue by sanketsuthar** [w3co/jcf#32]
How to solve this issue

**Comment by yazonnile** [comment]
Hi, sanketsuthar!
Could you plz attach some simple code example with issue?

**Comment by sanketsuthar** [comment]
[code.zip](https://github.com/w3co/jcf/files/406810/code.zip)


Thanks

**Comment by yazonnile** [comment]
@sanketsuthar,
there is problem in your code, yes.
But not with bootstrap.

This code broke jcf
```js
$(function ()
{
    $("#wizard").steps({
        headerTag: "h3",
        bodyTag: "section",
        transitionEffect: "slideLeft",
        stepsOrientation: "vertical"
    });
});
```
Think there are some dom mutation in steps plugin. So plz check it :)
Good luck

**Comment by sanketsuthar** [comment]
Thanks Buddy.

**Comment by sanketsuthar** [comment]
How to use jcf in wizard steps if it is possible to work in wizard plugin ?
