### ISSUE TITLE
Select first option not "selectable" again after change

### ISSUE THREAD

**Issue by ginesr** [w3co/jcf#33]
The default option is shown correctly, if is changed to something else that option is not available anymore
```
<select name="test">
 <option value="1">First Option</option>
 <option value="2">Second Option</option>
</select>
```

If option 2 is selected cannot go back and select option 1

**Comment by yazonnile** [comment]
Hi, @ginesr 
default option is a placeholder in select. So if you choose some real option - placeholder removes. And there is no chance to "unchoose" select, so it's not possible to go back to default option :)

Hope, this helps!

**Comment by ginesr** [comment]
Wait, is not just a placeholder, if I submit the form the value selected is sent, in my original example "First Option" is selected as it should, if nothing is changed and form is submitted value=1 is sent, so what I mean is that is not replicating behavior of a standard html-select

**Comment by inferpse** [comment]
@ginesr is this still an open issue?

All JCF elements should replicate the behavior of the standard elements.
Can you show a jsfiddle, so that we could reproduce it?

**Comment by ginesr** [comment]
Yes, is still happening, you can see it here
http://www.waituk.net/themes/html/entrada/elements-search-options.html
In "Select Your Destination" SPAIN is the first option, select another option, like DUBAI and then try to select SPAIN again

**Comment by inferpse** [comment]
@ginesr that's not the issue with the library. You have custom CSS code which hides first option from dropdown:

```css
.jcf-list ul li:first-child {
    display: none;
}
```

Just remove it and you should be good.
Please let me know if it worked for you.

**Comment by ginesr** [comment]
I'm closing this one, you were right it was css problem! Thanks
