### ISSUE TITLE
Which file should to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [w3co/jcf#34]
Hello @inferpse 
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
Which files need to be hosted?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8725

**Comment by inferpse** [comment]
Hey @kennynaoh !

Its a good idea! I think that you need to host all files under the `dist/` folder in this repo.
All of them are important but most of people probably use only _jcf.select.js_ and _jcf.scrollable.js_

**Comment by kennynaoh** [comment]
Thanks!

**Comment by kennynaoh** [comment]
Because there isn't has dist folder in `v1.0.0`~`v1.2.1`, but I think the file we need to add are `js/` and `css/` without `demo.css`, right?
Thanks!

**Comment by inferpse** [comment]
Yes, for these versions you could use files from `js/` folder. These files: _jquery.js_ and _ie.js_ shouldn't be hosted as well.

Since `1.2.2` we have minified files in `dist/` folder so maybe it's better to host them instead of the source files? Sorry for this mess in the repo :)

**Comment by kennynaoh** [comment]
Thanks a lot!

**Comment by inferpse** [comment]
Thanks to you!
I'll add the link to cdnjs in a project readme when jcf will be available there :)
