### ISSUE TITLE
Simulate click on select element

### ISSUE THREAD

**Issue by Aleksandern** [w3co/jcf#35]
Hello.

Is it possible to simulate click on select element with JavaScript/jQuery to open a dropdownlist?

something like this:
```
<select id="jcf-select">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</select>

jcf.click($("#jcf-select"));
```

Thanks.

**Comment by inferpse** [comment]
Hey, @Aleksandern !

If you're using custom dropdown option then you could use `showDropdown` method like this:
```js
jcf.getInstance($("#jcf-select")).instance.showDropdown();
```

There's no public API for this yet, because JCF aimed to support everything that native elements support, and there's no method `showDropdown` in native `<select>` element.

**Comment by Aleksandern** [comment]
Thanks, @inferpse
