### ISSUE TITLE
Native dropdown doesn't function correctly in chrome device emulator

### ISSUE THREAD

**Issue by wgwine** [w3co/jcf#36]
This is probably more of a chrome bug, as it only started happening in the latest update, but maybe there is something you can do to fix it. 
This problem only seems to occur when emulating devices in chrome dev tools and using the native dropdown, and does not appear to affect actual mobile devices.
You can see in this image that the dropdown is misaligned, and options are not selectable.

![image](https://cloud.githubusercontent.com/assets/2429681/18964376/a80986e0-8646-11e6-981d-db2ab7b58626.png)

**Comment by inferpse** [comment]
@wgwine looks like an issue in Chrome. This library does almost nothing when native dropdown option is enabled - it simply applies `opacity:0` to the original `<select>` and synchronizes state of fake element when original select changes it's value. It doesn't control the appearance and behavior of native dropdown.

What Chrome version are you using and what is your OS?

**Comment by wgwine** [comment]
Chrome Version 53.0.2785.143 m (64-bit)
Windows 10 version 1511

It's definitely a chrome thing though. I just reproduced it on a vanilla select. 

http://i.imgur.com/J7FbX3E.png

Maybe they will fix it eventually.
