### ISSUE TITLE
Scrollbar to selected option in select

### ISSUE THREAD

**Issue by suvsv** [w3co/jcf#38]
Thank you for your plugin.
Could you please supporting.
When a drop-down list in the select is opened, the scrollbar is set on the top options. Can we set scrollbar to selected option of the select (so selected option is visible in the list) programmatically?

**Comment by inferpse** [comment]
@suvsv 
You can use the same method which is used by the library itself. So something like this could work for you:

```js
var select = $('#my-select'),
    instance = jcf.getInstance(select);

select.prop('selectedIndex', 17);
instance.showDropdown();
instance.scrollToActiveOption();
```

**Comment by inferpse** [comment]
Looks like this is not an issue. Closing it.
