### ISSUE TITLE
React Component

### ISSUE THREAD

**Issue by sujameslin** [w3co/jcf#40]
Would you guys please provide information how to implement React Component?
I think its going to be tricky with React. 
Because react is not supposed to go along with jquery.

**Comment by yazonnile** [comment]
jcf still requires jquery, because we dont have enough time to make vanilla js version.
Its about jquery.
But working with react shouldnt really be a problem. In componentDidMount you could init jcf with any api call (jcf.replaceAll for example);

**Comment by sujameslin** [comment]
@yazonnile Yes, i think i didn't make it clear. 
With jQuery, its straightforward. We can just call `jcf.replaceAll` in component's `componentDidMount`. 
But jquery usage is not recommended way in react community. 
If you guys can make vanilla js version, it would be really great. 
Actually its what i was looking for in this PR.

**Comment by divined** [comment]
We have problem in react with clicking on the span - wrapper
It is not fired react onChange event =(

**Comment by yazonnile** [comment]
Show a component code please

**Comment by kissds** [comment]
Hi!
i have a same problem with onChange on input type="number"

i have tag
`<input
onChange={this.handlingQuantity.bind(this)}
required
ref="quantity"
name="quantity"
type="number"
min="1"
value={this.state.quantity}
max={this.state.unitsAvailable}
className="number form-control"
id="q-desk"/>
`
and handler

handlingQuantity(event) {
  this.setState({
      quantity: event.target.value
  });
}

But if i used jcf and click on jcf-btn-inc or jcf-btn-dec - onChange={this.handlingQuantity.bind(this)} don't work

All other plugins work fine: select, checkbox, radio, etc.

**Comment by kissds** [comment]
The matter was that onchange in javascript and onChange in React are different.
Clicking on .jcf-btn-inc works trigger in the plugin `this.realElement.val(newValue).trigger('change');`, but onChange in React does not work

I solved this problem like this
componentDidMount() {
        let self = this;
        document.getElementById('q-desk').onchange = function(e) {
            self.handlingQuantity(e, this.value);
        }
    }

handlingQuantity(event, eventValue) {
        this.setState({
            quantity: eventValue
        });
    }

**Comment by yazonnile** [comment]
Yes, because jquery and react have two different event models.
In your case you can do something like this
https://jsfiddle.net/m93gL86e/

All in all - you can create some Factory Component that will take only onChange function and will attach jquery onchange under the hood.
