### ISSUE TITLE
Checkbox wrapped in label = trouble

### ISSUE THREAD

**Issue by germansokolov13** [w3co/jcf#42]
If upon jcf.replacing the checkbox was wrapped in its own label it will not uncheck well. It sometimes unchecks and sometimes it doesn't. Looks like the toggle event is triggered twice because of it.

Many frameworks like Yii2 often wrap their checkboxes in label by default and in such situations it is very tricky to find out what goes wrong.

**Comment by TBschen** [comment]
+1, checkbox input inside label causes problems.

**Comment by yazonnile** [comment]
Just put correct ID-FOR attributes into checkbox-label and all works fine
https://jsfiddle.net/wdgumry4/
