### ISSUE TITLE
Text Input

### ISSUE THREAD

**Issue by julmot** [w3co/jcf#46]
Maybe I'm misunderstanding something, but why doesn't this library offer custom text fields too? Because it can be customized without JS? Even though this would be nice for a consistent look and feel out of the box.

**Comment by yazonnile** [comment]
Custom text field? Do you mean textarea?

**Comment by julmot** [comment]
Textarea and input. I mean they wouldn't require customization like a select field. However, just to make the list "complete" it would be a nice to have.

**Comment by yazonnile** [comment]
I think, jcf lib is about customizing form components in "js way"
Its not ui library for forms.
All you can customize by css - you should do that. Without jcf.

So, basically, you're right
> Because it can be customized without JS?

Yes
