### ISSUE TITLE
how to handle events, I just don't get it

### ISSUE THREAD

**Issue by buga1234** [w3co/jcf#47]
How I can get value on select change? Is there some information about this?

**Comment by inferpse** [comment]
@buga1234 you should listen regular DOM events on real form fields.
JCF simply creates a wrapper around native form elements and invokes proper events on native elements when needed.

**Comment by buga1234** [comment]
Yes, I've already found out how to do it. It took a lot of time to understand how catch events. Can you add some examples in documentation? It could help others in the future. Thanks for answer btw

**Comment by inferpse** [comment]
@buga1234 you're right. I've updated README.
