### ISSUE TITLE
Add jcf-selected class to the main span when item is selected

### ISSUE THREAD

**Issue by nramoneda** [w3co/jcf#49]
If we need to style different the select when an option is yet selected, we need a class or attribute that give this information. So it would great to add a jcf-selected class next to the jcf-select class.

<span class="jcf-select jcf-unselectable jcf-select-jcf-hidden  **jcf-selected**">
   <span class="jcf-select-text">
      <span class="">Herr</span>
   </span>
   <span class="jcf-select-opener"></span>
</span>

**Comment by yazonnile** [comment]
You can do it by your own
https://jsfiddle.net/wa5rqzyh/
