### ISSUE TITLE
How to trigger checkbox with JQuery 

### ISSUE THREAD

**Issue by Atranaz** [w3co/jcf#52]
Hello, 
can someone guide me how can i manually trigger checkbox of state checked i try to use this 

$('.jcf-checkbox').addClass('jcf-checkbox input-checked-parent jcf-checked');

It show me checked but not consider to be checked kindly guide me for this

Your help will appreciated thanks in Advance

**Comment by yazonnile** [comment]
Hi
```
$(myCheckbox).prop('checked', true);
jcf.refresh(myCheckbox);
```
