### ISSUE TITLE
JCF Select dropdown not the same width as the select

### ISSUE THREAD

**Issue by NigelOToole** [w3co/jcf#6]
When using the custom dropdowns for the JCF select they would sometimes not match up to the width of the select on the page. This seems to occur in a responsive design where the select is set to a percentage width. To resolve it I added the below to line 335 of jcf-select.js which makes the select on the page the same width as the custom dropdown.

this.fakeElement.css({
    width: selectWidth
});

I then remove this in the hideDropdown function.

this.fakeElement.attr('style', '');

**Comment by inferpse** [comment]
Hi, @NigelOToole !

JCF library tries to avoid inline styles on the fake select element so you don't have to worry about priority of your CSS rules vs inline html styles.

Responsive behavior can be achieved with CSS. For example you have:

```html
<select class="foo">...</select>
```

Now you can control styles of custom select like this:
```css
select.foo,
select.foo + .jcf-select {
    width: 50%;
}
```

Or you can use the `class` of your select element which is automatically copied and prefixed with `"jcf-select-"` by JCF library:
```css
.jcf-select-foo {
    width: 50%;
}
```

Will this work for your case?

**Comment by NigelOToole** [comment]
Hi

Thanks for the reply and I can understand trying to avoid inline styles but
this is the only way I could always get them to line up.

I have already tried using styles as suggested but this didnt work. The
strange thing is that my developer tools in firefox are saying all the
element, the native select, the jcf-select and the jcf-select-drop have the
same pixel width but the edges dont line up untill I added the inline
styles.

Regards,
Nigel

**Comment by inferpse** [comment]
Ok. Are you testing on the retina display?
Maybe you could provide a [jsfiddle](http://jsfiddle.net), so I can reproduce the issue?

BTW, you can try `fakeDropInBody: false` option which will put the drop inside the fake select element and it will have the same width as the container without any inline styles.

**Comment by inferpse** [comment]
Need more information to reproduce the issue.

**Comment by nikolai-katkov** [comment]
Having the same issue in Bootstrap 3. It is caused by jQuery outerWidth() behavior, it rounds the actual width. I managed to solve it in [jcf.select.js](https://github.com/w3co/jcf/blob/master/js/jcf.select.js), function `repositionDropdown' (line 309):
```
selectWidth = this.fakeElement.outerWidth(),
```
replace it with
```
selectWidth = this.fakeElement[0].getBoundingClientRect().width,
```
(see [stackoverflow](http://stackoverflow.com/questions/11907514/getting-the-actual-floating-point-width-of-an-element) to take care about browser support)

**Comment by nikolai-katkov** [comment]
If you wish, I could make a pull request (browser-safe version of this comment).

**Comment by inferpse** [comment]
Ok, so ```.offset()``` already returns floating point value and only width is calculated with rounded values. I think this is the only place that needs to be updated in _jcf.select_ module.

@nikolai-katkov will be waiting for your PR ;)
