### ISSUE TITLE
programmatically close dropdown when going out of focus

### ISSUE THREAD

**Issue by reicolee** [w3co/jcf#65]
currently, when using keyboard to navigate, users need to click enter to open the dropdown, and click enter again to close the dropdown. I tried using the refresh method, but it doesnt do anything, doesn't close the dropdown. Is there a way to close the dropdown programmatically?

**Comment by jastech2011** [comment]
I see you got it.

**Comment by yazonnile** [comment]
https://github.com/w3co/jcf/issues/75
