### ISSUE TITLE
How to hide the option from JCF dropdown when native select is hidden using method hide()

### ISSUE THREAD

**Issue by lovanjaneyulu** [w3co/jcf#70]
Hi we are using the JCF in our web application. 
we have 10 dropdowns with same options.
when user select a option from one dropdown this should be hide in other dropdowns

as we need to show the same option again on another scenario, we don't want to remove this option from dropdown.

we have used the jquery hide() method to hide the option, it works with native select but not reflects the JCF dropdown,

Please suggest a solution.

Thank you.

**Comment by yazonnile** [comment]
Here you go
https://jsfiddle.net/st6apo1d/2/
