### ISSUE TITLE
Have to use small hack with v-model checkboxes on vue.js 2.x

### ISSUE THREAD

**Issue by concept47** [w3co/jcf#72]
If you're dynamically updating checkboxes using two way binding with vue.js, you will not see the updates. What you have to do something like this

        // do something that updates the binding tied to a checkbox
        done = false // example

        setTimeout(() => {
          jcf.refresh("#css-id-of-your-checkbox")
        }, 50)

where the html/vue code looks like this

          <input type="checkbox"
            id="css-id-of-your-checkbox"
            v-model="done"></input>

**Comment by yazonnile** [comment]
Check `nextTick` part here
https://vuejs.org/v2/guide/reactivity.html
