### ISSUE TITLE
How can I close select dropdown programmatically?

### ISSUE THREAD

**Issue by zhil** [w3co/jcf#75]
I have a problem with React.js and jcf. 
I use custom select in Modal window and if I hit "ESC" after opening select - modal window is hidden, but popup - is not hidden

![jcf-bug](https://user-images.githubusercontent.com/981783/64919968-6632b980-d7ba-11e9-8228-782201ee343b.gif)

I have added sandbox to demostrate this bug - https://codesandbox.io/s/jcf-bug-sandbox-vl1vv

So, my question is How can I close select dropdown programmatically?

**Comment by zhil** [comment]
@jastech2011 @yazonnile I noticed, that you answered in a couple other recent issues, I would appreciate if you will write any ideas regarding how can I fix my bug

**Comment by yazonnile** [comment]
@zhil 
first of all - better **dont use this lib in the future, coz its not maintained anymore** at least as open source.
Second - use this function to close drop down 
```js
jcf.getInstance(YOUR_SELECT_NODE_ELEMENT).instance.hideDropdown();
```
