### ISSUE TITLE
JCF Select Doesn't work for GUID as ID

### ISSUE THREAD

**Issue by ntegral** [w3co/jcf#8]
We are using the JCF control as part of a project and the value is a GUID not an integer?  The control doesn't set the selected item?  How can this be corrected to work with GUID values?

**Comment by inferpse** [comment]
Hi, @ntegral !

Can you provide more information about which control was used (select, checkbox, radio, etc) and GUID value example?

**Comment by ntegral** [comment]
The select. For example the id= 6ea01f73-0532-4700-a351-831fab201a58 and the value = USA. Each country would have a different guid I'd.

Sent from my iPhone

On Jul 9, 2015, at 2:50 AM, Sergey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, @ntegral<https://github.com/ntegral> !

Can you provide more information about which control was used (select, checkbox, radio, etc) and GUID value example?

-

**Comment by ntegral** [comment]
Component source code
<select name="StateProvince" class="select" data-jcf='{"wrapNative": false }'
                                            ng-model="vm.contact.stateprovince"
                                            ng-options="s.id as s.value for s in vm.stateprovinces track by s.id"
                                            ng-change="vm.addTax(s.value)"
                                            required>
                                    </select>

Sample Json data:
{"stateProvinces":[{"label":"Alabama","value":"Alabama","id":"{EEF3C45E-72F9-DE11-BC84-0018FE280F2B}"},{"label":"Alaska","value":"Alaska","id":"{EFF3C45E-72F9-DE11-BC84-0018FE280F2B}"},{"label":"American Samoa","value":"American Samoa","id":"{F0F3C45E-72F9-DE11-BC84-0018FE280F2B}"},{"label":"Arizona","value":"Arizona","id":"{F1F3C45E-72F9-DE11-BC84-0018FE280F2B}"},{"label":"Arkansas","value":"Arkansas","id":"{F2F3C45E-72F9-DE11-BC84-0018FE280F2B}"},{"label":"Armed Forces Americas","value":"Armed Forces Americas","id":"{62F5B3F4-F338-DF11-B6BB-0018FE280F2B}"},{"label":"Armed Forces Europe","value":"Armed Forces Europe","id":"{63F5B3F4-F338-DF11-B6BB-0018FE280F2B}"}]}

The selected item on the select is not being updated.  The selected text is being updated.  However the selected attribute is not being updated.
[cid:image001.png@01D0BA1F.536ED7B0]
Assistance on how to get this working would be greatly appreciated.

Dexter

**Comment by inferpse** [comment]
Ok. I've created [plnkr](http://plnkr.co/edit/FFqKkZ?p=preview) to test the issue, but I don't see any problems. Do you use `jcf.angular.js` directive and `jcf` attribute on `<select>` tag? Or you're trying to customize form elements with jQuery and `jcf.replaceAll()` method?

To make JCF work properly with Angular you'll have to use a directive, not `jcf.replaceAll()` method (see my example link above).

**Comment by inferpse** [comment]
@ntegral if that doesn't work for you please post more information here.
